### ISSUE TITLE
Having trouble with the learn gem

### ISSUE THREAD

**Issue by cmrberry** [learn-co-curriculum/learn-environment-setup#2]
Hi! Really excited to try this out :smile: I'm currently having trouble with the learn gem though. I've been following all of the manual setup steps here:

https://learn.co/osx/skip

The learn gem installed ok, but when I run `learn whoami` or just `learn`, this is what I get:

```
$ learn whoami
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': /Library/Ruby/Gems/2.0.0/gems/learn-co-3.2.18/lib/learn/options_sanitizer.rb:123: syntax error, unexpected ',' (SyntaxError)
    def rebuild_args!(flag_arg:, add_test_command:)
                                ^
/Library/Ruby/Gems/2.0.0/gems/learn-co-3.2.18/lib/learn/options_sanitizer.rb:221: syntax error, unexpected keyword_end, expecting end-of-input
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/learn-co-3.2.18/lib/learn.rb:7:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/learn-co-3.2.18/bin/learn:3:in `<top (required)>'
    from /usr/local/bin/learn:23:in `load'
    from /usr/local/bin/learn:23:in `<main>'
```

Here's my Ruby version:

```
$ ruby -v
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
```

Is there a minimum version I need to be at? If so, can that be specified in the documentation for those of us who are installing manually and already have Ruby installed? Thanks!

**Comment by AnnJohn** [comment]
Hi @cmrberry sorry for the delay on this. If you're still having trouble with this, please use the Ask a Question tool in Learn and someone will help you with this right away. Thanks!

**Comment by randi274** [comment]
Just in case anyone else stumbles upon this post and is stuck with the same error, I had to update my version of Ruby to the most current version using RVM, and had to ensure my RVM was correctly installed too.

**Comment by cmrberry** [comment]
@randi274 Same here, I should have come back and posted what I figured out. Thanks!

**Comment by fhernandez173** [comment]
I am having this issue. I am currently using ruby-2.3.0 and rvm 1.27.0 (latest). Anyone knows more about this issue? I installed Ruby through RVM. Which version is lear supported on? Odd it keeps saying I am using ruby 2.0.0. How do I change this?

**Comment by AnnJohn** [comment]
hi @cmrberry, we are using an Integrated Development Environment now with Learn. To get set up go to learn.co/ide to download it. Thanks
